LFP Classification: preprocessing Namespace Reference
preprocessing Namespace Reference
Functions
def load_lfp_data (file=LFP[771], channels=EC014_41_NUMBER_OF_CHANNELS)
Loads the LFP signals from a .eeg file (LFP Data only f < 625Hz) or a .dat file (LFP Data + Spikes).
def load_angles_data (file=ANGLES[771], degrees=True)
Loads the animal position data from a .whl file which contain 2 (x, y) pairs, one for each LED.
def downsample_lfps (lfp_data, orig_rate, new_rate)
Downsample the LFP signal data after applying an anti-aliasing filter.
def angles_expansion (angles_data, orig_rate, new_rate)
Fill angular data with 'NaN' values to match an expected sampling rate.
def shortest_angle_interpolation (start, end, amount)
This interpolation method considers the 'start' and 'end' as angles in a circumference where the objective is to find the smallest arch between two angles.
def vectorized_sai (angles_data)
Replace 'NaN' values between valid values (interpolation) in angular data with an interpolated value using the shortest angle interpolation.
def interpolate_angles (angles_data, method="Shortest Angle")
Replace 'NaN' values in angular data with an interpolated value using a given method.
def add_labels (lfps, angles, round_labels, start=0, offset=30)
Add an additional column to the LFP signals matrix with the angular data used as the labels.
def clean_invalid_positional (labeled_dataset, is_padded=True)
Clean the data rows which have '-1' values as labels (angles) from the the data and their LFPs associated in each channel.
def ndarray_to_dataframe (dataset, rate)
Converts an n-D Numpy array to a Pandas Dataframe.
def channels_to_windows (series, channel, window_size, batch_size, shuffle_buffer=None, offset=1)
Receives a numpy array containing the time series of LFP signals of n channels and returns the same data, separated in windows.
def average_angles (angles, window_size)
Receives a numpy array containing the time series of the angles and returns the an set of windows with the average of the 'window_size' angles in each window.
Variables
PATH_TO_DATASETS = os.path.join(Env.CURRENT_FOLDER, "../Datasets/")
dictionary LFP
dictionary ANGLES
int RAW_DATAMAX_SAMPLING_RATE = 20000
int RAW_NEURALYNX_SAMPLING_RATE = 32552
int LFP_DATAMAX_SAMPLING_RATE = 1250
int LFP_NEURALYNX_SAMPLING_RATE = 1252
float POSITION_DATA_SAMPLING_RATE = 39.06
int EC014_41_NUMBER_OF_CHANNELS = 99
Function Documentation
add_labels()
def preprocessing.add_labels (lfps, angles, round_labels, start = 0, offset = 30)
Add an additional column to the LFP signals matrix with the angular data used as the labels.
Parameters
lfps Matrix [n x numChannels] with the LFP signals used as the preliminary features of the data.
angles Array with the angles data extracted from the positions used as the labels of the data.
round_labels Boolean, if true the labels are rounded to angles multiples of 'offset' starting from 'start'
start Angle in [0째, 360째[ used as first label.
offset Offset in [1째, 360째[ between labels starting from 'start' angle.
Returns
labeled_data: Matrix with the labeled data [n x lfps[numChannels], angles].
Definition at line 239 of file preprocessing.py.
angles_expansion()
def preprocessing.angles_expansion (angles_data, orig_rate, new_rate)
Fill angular data with 'NaN' values to match an expected sampling rate.
Usually the position data is acquired at a lower sampling rate than the LFP signals.
Assuming that the acquisition of data started and stopped at the same time, then no data has to be added after the last sample.
Parameters
angles_data Array with the angles data extracted from the animal positions.
orig_rate Sampling rate originally used to acquire the data.
new_rate New sampling rate of the data. The gaps are filled with 'NaN'.
Returns
upsampled_data: Original data filled with 'NaN' to match the new sampling rate.
Definition at line 135 of file preprocessing.py.
average_angles()
def preprocessing.average_angles (angles, window_size)
Receives a numpy array containing the time series of the angles and returns the an set of windows with the average of the 'window_size' angles in each window.
Each window is 1 element shifted from the previous window.
Parameters
angles Numpy Array with the Angles data to use as the labels.
window_size Size of the windows in which the data are being split.
Returns
average_angles: Averaged Angles data separated in windows.
Definition at line 423 of file preprocessing.py.
channels_to_windows()
def preprocessing.channels_to_windows (series, channel, window_size, batch_size, shuffle_buffer = None, offset = 1)
Receives a numpy array containing the time series of LFP signals of n channels and returns the same data, separated in windows.
Parameters
series Numpy Array with the LFP data of the n channels.
channel Channel to use.
window_size Size of the windows in which the data are being split.
batch_size Number of pairs data-labels to group as a batch
shuffle_buffer Number of windows to shuffle at the same time.
offset Number of samples to shift between windows.
Returns
windowed_ds: LFP data of the selected channel separated in windows.
Definition at line 378 of file preprocessing.py.
clean_invalid_positional()
def preprocessing.clean_invalid_positional (labeled_dataset, is_padded = True)
Clean the data rows which have '-1' values as labels (angles) from the the data and their LFPs associated in each channel.
Plus the following 31 rows with NaN as angle value in case of padded data.
The positional data taken from the LEDs placed in the rat have discontinuities where one or both LEDs are lost, making them invalid. Hence '-1' values are used instead to denote invalid position data and are meant to be removed from the data since they are not representative labels.
Parameters
labeled_dataset Matrix [n x (numChannels +1)] with the LFP signals used as the preliminary features of the data and the angles data extracted from the positions used as the labels of the data.
is_padded If True, manage the input labeled dataset as a padded array of angles, or a downsampled LFP set otherwise.
Returns
clean_dataset: Input data without invalid positional values.
Definition at line 287 of file preprocessing.py.
downsample_lfps()
def preprocessing.downsample_lfps (lfp_data, orig_rate, new_rate)
Downsample the LFP signal data after applying an anti-aliasing filter.
An order 8 Chebyshev type I filter is used. Usually the LFP signals are acquired at a higher sampling rate than the position data.
Note
: This method assumes that the reason of frequencies is 32 to compute the decimation.
Parameters
lfp_data Matrix [n x numChannels] with the LFP signals
orig_rate Sampling rate originally used to acquire the data.
new_rate New sampling rate of the data.
Returns
resampled_data: Original data downsampled to the new rate.
Definition at line 108 of file preprocessing.py.
interpolate_angles()
def preprocessing.interpolate_angles (angles_data, method = "Shortest Angle")
Replace 'NaN' values in angular data with an interpolated value using a given method.
Parameters
angles_data Array with the angles data extracted from the animal positions.
method Interpolation method to fill the gaps in the data. The optional methods available are the supported by pandas.DataFrame.interpolate function, which are: 'linear', 'quadratic', 'cubic', 'polynomial', among others.
Returns
interpolated_angles: Array with the angles data interpolated using the given method.
Definition at line 211 of file preprocessing.py.
References vectorized_sai().
load_angles_data()
def preprocessing.load_angles_data (file = ANGLES[771], degrees = True)
Loads the animal position data from a .whl file which contain 2 (x, y) pairs, one for each LED.
If any position value equals '-1' then it's replaced with 'NaN' instead.
Parameters
file Path to the file containing the animal LED's position information
degrees If this flag is set, then the angles are returned in degrees from [0, 360[, or radians otherwise.
Returns
angles: Array with the angles in radians extracted from the positions. The angles are given as float16 values calculated as arctan(y2 - y1 /x2 - x1). Unless the denominator is 0, in that case '0' is returned for that element.
Definition at line 71 of file preprocessing.py.
load_lfp_data()
def preprocessing.load_lfp_data (file = LFP[771], channels = EC014_41_NUMBER_OF_CHANNELS)
Loads the LFP signals from a .eeg file (LFP Data only f < 625Hz) or a .dat file (LFP Data + Spikes).
Parameters
file Path to the file containing the animal LFP data.
channels Number of recorded channels in LFP signals file.
Returns
lfp: Array (n x channels) with the data. With the columns being the channels and the rows the a different time step.
Definition at line 48 of file preprocessing.py.
ndarray_to_dataframe()
def preprocessing.ndarray_to_dataframe (dataset, rate)
Converts an n-D Numpy array to a Pandas Dataframe.
Parameters
dataset Matrix [n x (numChannels +1)] with the LFP signals used as the preliminary features of the data and the angles data extracted from the positions used as the labels of the data.
rate
Returns
dataframe: Pandas data frame with Channels 0-99 and Angles as columns names, and the timestamp as indexes calculated as 1/rate * 1e6 to get the time step of the acquisition in microseconds.
Definition at line 352 of file preprocessing.py.
shortest_angle_interpolation()
def preprocessing.shortest_angle_interpolation (start, end, amount)
This interpolation method considers the 'start' and 'end' as angles in a circumference where the objective is to find the smallest arch between two angles.
param start: Start angle with values in the range of [0 to 360[ param end: Final angle with values in the range of [0 to 360[ param amount: Value between [0, 1] which determines how close the interpolated angle will be placed from the Start angle (0) or from the Final angle (1), being 0.5 the middle. return interpolated_angle: Interpolated angle between 'start' and 'end'.
Definition at line 160 of file preprocessing.py.
Referenced by vectorized_sai().
vectorized_sai()
def preprocessing.vectorized_sai (angles_data)
Replace 'NaN' values between valid values (interpolation) in angular data with an interpolated value using the shortest angle interpolation.
param angles_data: Array with the angles data extracted from the animal positions. return interpolated_angles: Array with the angles data interpolated using the Shortest Angle Interpolation
Definition at line 173 of file preprocessing.py.
References shortest_angle_interpolation().
Referenced by interpolate_angles().
Variable Documentation
ANGLES
dictionary preprocessing.ANGLES
Initial value:
 =  {765: PATH_TO_DATASETS + "ec014.765.whl",
           771: PATH_TO_DATASETS + "ec014.771.whl"}
Definition at line 28 of file preprocessing.py.
EC014_41_NUMBER_OF_CHANNELS
int preprocessing.EC014_41_NUMBER_OF_CHANNELS = 99
Definition at line 37 of file preprocessing.py.
LFP
dictionary preprocessing.LFP
Initial value:
 =  {765: PATH_TO_DATASETS + "ec014.765.eeg",
        771: PATH_TO_DATASETS + "ec014.771.eeg"}
Definition at line 26 of file preprocessing.py.
LFP_DATAMAX_SAMPLING_RATE
int preprocessing.LFP_DATAMAX_SAMPLING_RATE = 1250
Definition at line 34 of file preprocessing.py.
LFP_NEURALYNX_SAMPLING_RATE
int preprocessing.LFP_NEURALYNX_SAMPLING_RATE = 1252
Definition at line 35 of file preprocessing.py.
PATH_TO_DATASETS
preprocessing.PATH_TO_DATASETS = os.path.join(Env.CURRENT_FOLDER, "../Datasets/")
Definition at line 25 of file preprocessing.py.
POSITION_DATA_SAMPLING_RATE
float preprocessing.POSITION_DATA_SAMPLING_RATE = 39.06
Definition at line 36 of file preprocessing.py.
RAW_DATAMAX_SAMPLING_RATE
int preprocessing.RAW_DATAMAX_SAMPLING_RATE = 20000
Definition at line 32 of file preprocessing.py.
RAW_NEURALYNX_SAMPLING_RATE
int preprocessing.RAW_NEURALYNX_SAMPLING_RATE = 32552
Definition at line 33 of file preprocessing.py.