LFP Classification: Predictor Namespace Reference
Predictor Namespace Reference
Functions
def predictor ()
Function Documentation
predictor()
def Predictor.predictor ()
Predictor
Experiment Setup
Initialize Environment
Initialize Tensorflow session.
Set seed for Numpy and Tensorflow
Specify run configuration parameters.
Specify run configuration parameters.
Specify dataset generation parameters.
Specify model's training parameters.
Procedure
Step 1: Import training, validation and test datasets of LFPs as inputs and Angles as labels.
Step 2: Convert data to windowed series.
Step 3: Create the model with the specified parameters
Step 4: Train the model with the training and validation data.
Step 5: Plotting the original angular data vs the predictions for a determined number of batches
Finish Test and Exit: Save logs, captures and results.
Definition at line 53 of file Predictor.py.
References models.cnn(), models.compile_and_fit(), models.lstm(), and models.mlp().