LFP Classification: models Namespace Reference
models Namespace Reference
Functions
def mlp (layers, units_per_layer, dropout=None)
Defines a classical neural network sometimes called: Multi-Layer Perceptron.
def cnn (inputs, units_per_layer)
Creates a model of a Convolutional Neural Network with a Conv1D as the input layer, one dense as the only hidden layer and another dense with only 1 neuron as the output layer.
def lstm (units_per_layer)
Creates a model of a Long Short-Term Memory Neural Network as the input layer, one dense with only 1 neuron as the output layer.
def compile_and_fit (model, train, val, epochs=20, patience=2)
Fits the provided training data in the specified model and train's it.
Function Documentation
cnn()
def models.cnn (inputs, units_per_layer)
Creates a model of a Convolutional Neural Network with a Conv1D as the input layer, one dense as the only hidden layer and another dense with only 1 neuron as the output layer.
The first two layer has ReLU activation and the last one uses a linear activation function.S
Parameters
inputs Number of inputs of the network. It is used as the kernel size with the intention that the 1D convolutional layer outputs a single value throughout the specified number of filters.
units_per_layer Specified the number of neurons of the hidden dense layer, which has to match with the number of filters that will output a result in the 1D convolutional input layer.
Returns
conv_model: The model of the CNN created for later usage as the predictor.
Definition at line 82 of file models.py.
Referenced by Predictor.predictor().
compile_and_fit()
def models.compile_and_fit (model, train, val, epochs = 20, patience = 2)
Fits the provided training data in the specified model and train's it.
The validation data is used to compare the performance of the model against unknown data. MSE is used as the cost function to train the model and MAE as the performance evaluation metric.
Parameters
model Model to train. It can be a MLP, CNN or LSTM, among others.
train The dataset for training the model. Must have the shape: (batch, time, features)
val The dataset for validating the model. Must have the shape: (batch, time, features)
epochs Number of iteration over the entire set of data (all the batches).
patience Number of epochs to wait for improvement in the metrics. If there is no notorious improvement in the performance of the validation set after the 'patience' epochs, the training will stop at this point.
Returns
history: The results of the training.
Definition at line 134 of file models.py.
Referenced by Predictor.predictor().
lstm()
def models.lstm (units_per_layer)
Creates a model of a Long Short-Term Memory Neural Network as the input layer, one dense with only 1 neuron as the output layer.
The activation functions of the LSTM layer are the regular ones for each of it's gates.
Parameters
units_per_layer Number of inputs of the network.
Returns
lstm_model: The model of the LSTM created for later usage as the predictor.
Definition at line 105 of file models.py.
Referenced by Predictor.predictor().
mlp()
def models.mlp (layers, units_per_layer, dropout = None)
Defines a classical neural network sometimes called: Multi-Layer Perceptron.
It is Feedforward and fully-connected, with the specified parameters. The activation function of the hidden layers is ReLU, and the activation of the output is linear.
Parameters
layers Number of hidden layers (besides the input and outputs ones).
units_per_layer Number of neurons per layer. Applies to all layers except for the last one which has only 1: the predicted angle.
dropout A value between 0 and 1 of neuron's results to discard of the training. If provided, two layers of this regularization method will be added to the model. One after the input layer and one before the output layer.
Returns
model: The model of the MLP created for later usage as the predictor.
Definition at line 32 of file models.py.
Referenced by Predictor.predictor().