LFP Classification: Environment Namespace Reference
Environment Namespace Reference
Functions
def init_environment (print_the_header=False, enable_debug=False)
Initialize the directories and files to log the results.
def print_text (text)
Print a passed text and save it in the yomchi_log.txt.
def print_box (text)
Print a passed text in a box and save it in the yomchi_log.txt.
def step (description=None, new_step_number=0)
Print the current step number with a brief description.
def print_parameters (params_dictionary)
Print a list of parameters.
def log_versions ()
Stores the environment versions including packages, libraries and OS.
def print_header ()
Print a header in the console output and log files.
def finish_test (rename_results_folder=None)
Safely finish the test run and log some final information.
Variables
START_TIME = datetime.datetime.now()
CURRENT_FOLDER = os.getcwd()
string RESULTS_FOLDER = CURRENT_FOLDER + "/Results-" + START_TIME.strftime("%Y-%m-%d_%H-%M") + "/"
string LOGS_FOLDER = RESULTS_FOLDER + "Logs/"
string CAPTURES_FOLDER = RESULTS_FOLDER + "Captures/"
string VERSIONS_LOG_PATH = LOGS_FOLDER + "versions_log.txt"
string YOMCHI_LOG_PATH = LOGS_FOLDER + "yomchi_log.txt"
int LINE_LENGTH = 100
int step_number = 1
versions_log = None
yomchi_log = None
caller_file = None
bool debug = False
Function Documentation
finish_test()
def Environment.finish_test (rename_results_folder = None)
Safely finish the test run and log some final information.
Parameters
rename_results_folder Optional name for the results folder.
Returns
None
Definition at line 248 of file Environment.py.
References print_text().
init_environment()
def Environment.init_environment (print_the_header = False, enable_debug = False)
Initialize the directories and files to log the results.
Parameters
print_the_header If True, print the header
enable_debug If True, run some code to help debugging
Definition at line 49 of file Environment.py.
References log_versions(), and print_header().
log_versions()
def Environment.log_versions ()
Stores the environment versions including packages, libraries and OS.
Returns
None
Definition at line 177 of file Environment.py.
Referenced by init_environment().
print_box()
def Environment.print_box (text)
Print a passed text in a box and save it in the yomchi_log.txt.
Parameters
text Text to print
Returns
None
Definition at line 96 of file Environment.py.
References print_text().
Referenced by step().
print_header()
def Environment.print_header ()
Print a header in the console output and log files.
Returns
None
Definition at line 223 of file Environment.py.
References print_text().
Referenced by init_environment().
print_parameters()
def Environment.print_parameters (params_dictionary)
Print a list of parameters.
Parameters
params_dictionary Dictionary of parameters {name: value} to print.
Returns
None
Definition at line 149 of file Environment.py.
References print_text().
print_text()
def Environment.print_text (text)
Print a passed text and save it in the yomchi_log.txt.
Parameters
text Text to print
Returns
None
Definition at line 83 of file Environment.py.
Referenced by finish_test(), print_box(), print_header(), and print_parameters().
step()
def Environment.step (description = None, new_step_number = 0)
Print the current step number with a brief description.
Parameters
description Description of the step.
new_step_number If defined, reset the steps numeration to the passed value.
Returns
None
Definition at line 126 of file Environment.py.
References print_box().
Variable Documentation
caller_file
Environment.caller_file = None
Definition at line 39 of file Environment.py.
CAPTURES_FOLDER
string Environment.CAPTURES_FOLDER = RESULTS_FOLDER + "Captures/"
Definition at line 30 of file Environment.py.
CURRENT_FOLDER
Environment.CURRENT_FOLDER = os.getcwd()
Definition at line 27 of file Environment.py.
debug
bool Environment.debug = False
Definition at line 40 of file Environment.py.
LINE_LENGTH
int Environment.LINE_LENGTH = 100
Definition at line 33 of file Environment.py.
LOGS_FOLDER
string Environment.LOGS_FOLDER = RESULTS_FOLDER + "Logs/"
Definition at line 29 of file Environment.py.
RESULTS_FOLDER
string Environment.RESULTS_FOLDER = CURRENT_FOLDER + "/Results-" + START_TIME.strftime("%Y-%m-%d_%H-%M") + "/"
Definition at line 28 of file Environment.py.
START_TIME
Environment.START_TIME = datetime.datetime.now()
Definition at line 26 of file Environment.py.
step_number
int Environment.step_number = 1
Definition at line 36 of file Environment.py.
versions_log
Environment.versions_log = None
Definition at line 37 of file Environment.py.
VERSIONS_LOG_PATH
string Environment.VERSIONS_LOG_PATH = LOGS_FOLDER + "versions_log.txt"
Definition at line 31 of file Environment.py.
yomchi_log
Environment.yomchi_log = None
Definition at line 38 of file Environment.py.
YOMCHI_LOG_PATH
string Environment.YOMCHI_LOG_PATH = LOGS_FOLDER + "yomchi_log.txt"
Definition at line 32 of file Environment.py.